site:
    resource: "@SiteBundle/Controller/"
    type:     annotation
  

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation


app:
    resource: "@AppBundle/Controller/"
    type:     annotation
